### ISSUE TITLE
/ReactNativeFFmpegTest.app/colosseum.jpg: No such file or directory

### ISSUE THREAD

**Issue by idoor88** [tanersener/react-native-ffmpeg#58] opened 2019-04-07 01:36 UTC
I got the ReactNativeFFmpegTest app built and installed on my iphone device, it works when I use -version command, but when I switched to VIDEO tab and tap on CREATE button, it showed a message saying:

/var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/colosseum.jpg: No such file or directory.

also in my console log, I saw the jpg files saved:
Saved resource colosseum.jpg to /var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/colosseum.jpg
Main.js:285 Saved resource pyramid.jpg to /var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/pyramid.jpg
Main.js:288 Saved resource tajmahal.jpg to /var/containers/Bundle/Application/DF534C28-4412-4F59-AB33-9B486C4DAB86/ReactNativeFFmpegTest.app/tajmahal.jpg

react-native info

info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 33.05 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
yarn install v0.15.1
success Already up-to-date.
Done in 0.19s. - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8 => 16.8.6 
      react-native: ^0.59 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-cn-richtext-editor: 1.0.33
      react-native-git-upgrade: 0.2.7

**Comment by tanersener** [comment] 2019-04-07 05:21
duplicate of tanersener/react-native-ffmpeg-test#4

**Closed by tanersener** 2019-04-07 05:21 UTC
Labels: duplicate
